version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - restore_cache:
          key: circleci-gexecutor-favicon-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-gexecutor-favicon-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/executor-favicon.hpi

